owner: getqarote
repo: status

sites:
  - name: Website
    url: https://qarote.io
  - name: App
    url: https://app.qarote.io
  - name: API
    url: https://api.qarote.io/livez
  - name: Portal
    url: https://portal.qarote.io
  - name: Demo
    url: https://demo.qarote.io

status-website:
  cname: status.qarote.io
  logoUrl: https://qarote.io/favicon.ico
  name: Qarote Status
  introTitle: "Qarote System Status"
  introMessage: Real-time uptime monitoring for all Qarote services.
  navbar:
    - title: Status
      href: /
    - title: Qarote
      href: https://qarote.io
    - title: GitHub
      href: https://github.com/getqarote/status
